### ISSUE TITLE
Replace http links with https links

### ISSUE THREAD

**Issue by reactormonk** [dvatvani/dvatvani.github.io#1]
Replace the links (e.g. https://github.com/dvatvani/dvatvani.github.io/blob/master/BGG-Analysis-Part-1.html#L6 ) with https links or remove the protocol or host, so the website renders properly:

> BGG-Analysis-Part-2.html:6 Mixed Content: The page at 'https://dvatvani.github.io/BGG-Analysis-Part-2.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://dvatvani.github.io/theme/stylesheet/style.min.css'. This request has been blocked; the content must be served over HTTPS.

**Comment by mabrowning** [comment]
I use (and recommend!) the extension [HTTPS everywhere](https://www.eff.org/https-everywhere), and your site is accessible over HTTPS, but broken.

(Still, a very nice analysis, and after disabling my extension I was able to view your post!)

**Comment by dvatvani** [comment]
A couple of years late, but I've finally managed to resolve this. Thanks for letting me know.
